# Generated by Django 4.2.5 on 2023-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_scoringmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringmodel',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='scoringmodelhistory',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
