# Generated by Django 4.2.5 on 2023-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_scoringmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countedattributes',
            name='scoring_name',
            field=models.ManyToManyField(blank=True, to='backend.scoringmodel'),
        ),
    ]
